apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: statsd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: statsd
    spec:
      containers:
      - name: statsd
        image: hyperpilot/statsd:latest
        ports:
        - containerPort: 8125
        - containerPort: 8126
        volumeMounts: []
      volumes: []
