apiVersion: v1
kind: Service
metadata:
  name: resource-worker
  labels:
    app: resource-worker
spec:
  clusterIP: None
  ports:
    - port: 7998
      name: resource-worker
  selector:
    app: resource-worker
