apiVersion: v1
kind: Service
metadata:
  name: resource-worker-service
spec:
  selector:
    app: resource-worker
    podId: resource-worker-0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7998
